# Executable names:
EXE = lab_flow
TEST = test

# Add all object files needed for compiling:
EXE_OBJ = main.o
OBJS = graph.o main.o NetworkFlow.o

# Use the cs225 makefile template:
include cs225/make/cs225.mk
